### ISSUE TITLE
Columns not aligning in matrixinput

### ISSUE THREAD

**Issue by SusmithBarigidad** [INWTlab/shiny-matrix#13]
Hi Team,
Columns are not aligned when there are more than 1 columns in the matrix.
Please find the attached image for reference :
<img width="474" alt="RshinyMatrixIssue" src="https://user-images.githubusercontent.com/31435515/84361976-1c142280-abea-11ea-819f-8ff11b3a009a.png">

**Comment by aneudecker** [comment]
Hi @SusmithBarigidad,

thanks for reporting this. Could you provide a minimal code example and describe what you mean by "not aligned"?

**Comment by SusmithBarigidad** [comment]
m <- matrix(runif(12), 6, 2, dimnames = list(NULL, c("x", "y")))
ui <- fluidPage(   titlePanel("shinyMatrix: Simple App"),       
    matrixInput( "sample", value = m, rows = list( extend = FALSE),      
    cols = list( names = TRUE )     )   )
   
server <- function(input, output, session) {
   output$scatter <- renderPlot({
   plot(input$sample, col = "red", main = "Scatterplot")  
   }) }
shinyApp(ui, server)

Please find the code minimal attached, "not aligned" : i mean to say that column names 'x' and 'y' will be not structured as per columns : same example is shown in the above screenshot for column names - 'Monthly Paid' and 'Yearly Paid ' i assume this is html bug

**Comment by aneudecker** [comment]
@SusmithBarigidad I cannot reproduce this. With the code you provided I get on Google Chrome

![image](https://user-images.githubusercontent.com/5587462/84747074-1d14cd80-afb7-11ea-9b1c-9d6045f85d3e.png)

Which browser are you using?

**Comment by SusmithBarigidad** [comment]
@aneudecker  We also used google chrome but not getting the same output

**Comment by aneudecker** [comment]
Which version of shinyMatrix are you using? Please try to install the current version using `devtools::install_github("shinyMatrix")`
