### ISSUE TITLE
How to Read the individual elements of the matrix

### ISSUE THREAD

**Issue by SatendraLV** [INWTlab/shiny-matrix#15]
Hi, 
I was trying to read the elements of the matrix, that i created using matrixInput. 
I was getting an error to use reactive elements or event handler, but even after not able to extract the element of matrix.

Same is working if i am using render table.

Can you help on this?

Thanks 
Satendra

**Comment by SatendraLV** [comment]
This is the error i am getting when i am referring to

mat <- input$matrix

//

Warning: Error in .getReactiveEnvironment()$currentContext: Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
  56: stop
  55: .getReactiveEnvironment()$currentContext
  54: getCurrentContext
  50: .subset2(x, "impl")$get
  49: $.reactivevalues

//

**Comment by aneudecker** [comment]
Hi @SatendraLV 

you can only use this function as part of a shiny app. It seems like you try to execute this commands directly in the console. Have a look at the examples, i.e in https://github.com/INWTlab/shiny-matrix/tree/master/inst/app

You can create these two files in a folder on your pc and start the app by running `shiny::runApp()` in this folder

If you are new to the shiny world, this might also make sense for you: https://shiny.rstudio.com/tutorial/

All the best!
