### ISSUE TITLE
Can this package support an upper triangular matrix input? 

### ISSUE THREAD

**Issue by HaipengU** [INWTlab/shiny-matrix#16]
Thanks for creating this package, and I found it is very useful.  I intended to use this matrix input to collect variance-covariance components as user input. As the variance-covariance matrix is symmetric, which means I only need the upper triangle rather than the whole matrix input. I was wondering if this package supports an upper triangular matrix input?

**Comment by aneudecker** [comment]
Hi @HaipengU,

I am glad you find the package useful! Out the box the package only provides full matrix inputs. One idea would be to use CSS to hide the fields in the lower triangular matrix, but unfortunately there is no selector in CSS to select "row index larger than column index". So the only option here for now would be to use some custom javascript to hide these fields. You would need to call this function every time the matrix dimension changes.

It will probably easier to change the package to include this information in a CSS class during the generation of the table cells - i.e. here:

https://github.com/INWTlab/shiny-matrix/blob/master/inst/www/matrixInput.js#L27

I will include this in the next release (which will not happen too soon), PRs are welcome though!

**Comment by HaipengU** [comment]
> Hi @HaipengU,
> 
> I am glad you find the package useful! Out the box the package only provides full matrix inputs. One idea would be to use CSS to hide the fields in the lower triangular matrix, but unfortunately there is no selector in CSS to select "row index larger than column index". So the only option here for now would be to use some custom javascript to hide these fields. You would need to call this function every time the matrix dimension changes.
> 
> It will probably easier to change the package to include this information in a CSS class during the generation of the table cells - i.e. here:
> 
> https://github.com/INWTlab/shiny-matrix/blob/master/inst/www/matrixInput.js#L27
> 
> I will include this in the next release (which will not happen too soon), PRs are welcome though!

Hi Andreas, thank you for your reply and suggestion. I just saw the message and I actually ended up putting "NA" in the lower triangle of the matrix temporarily. I believe it will be great to have an option to select either full or only the upper/lower triangle of the matrix in the next release. Thanks!
