### ISSUE TITLE
Styling not working for ShinyMatrix

### ISSUE THREAD

**Issue by claycantrell** [INWTlab/shiny-matrix#18]
Hello!

I have not been able to get shiny-matrix to display in the proper stylized format with grid lines and such. 

I have provided a simple example program I found on the internet, which seems to load fine in the example, and a screenshot of how the application looks when I load it on my computer.

<img width="1440" alt="Screen Shot 2021-04-15 at 6 06 53 PM" src="https://user-images.githubusercontent.com/77699867/114957246-7d61df00-9e15-11eb-9b9d-23e081b75087.png">

Any help would be greatly appreciated. 

Thanks!

-Clay

[app.R.zip](https://github.com/INWTlab/shiny-matrix/files/6321846/app.R.zip)

**Comment by aneudecker** [comment]
Hi @claycantrell,

thanks for reporting this! The reason for this is that an updated shiny version included different css classes. In the new development version on GitHub this should be fixed as we include our own set of styles.

**Comment by claycantrell** [comment]
Hi @aneudecker, thanks for getting back to me!

Is it possible to delete the row and column name cells on the far left and top of the matrix? I can remove the names but I can't seem to be able to get rid of the cells as well.

**Comment by aneudecker** [comment]
Could you post the code how you are creating the matrix and a screenshot? It should be possible to achieve this with the correct parameters

**Comment by claycantrell** [comment]
I can't seem to find a parameter that fits the bill from this source.
https://cran.r-project.org/web/packages/shinyMatrix/readme/README.html

Let me know if I'm missing something.
Once again, thanks for the help!

<img width="645" alt="Screen Shot 2021-05-14 at 1 44 59 PM" src="https://user-images.githubusercontent.com/77699867/118329181-8220be00-b4bb-11eb-83cb-6e7926e7dc3a.png">

<img width="1440" alt="Screen Shot 2021-05-14 at 1 45 47 PM" src="https://user-images.githubusercontent.com/77699867/118329220-8d73e980-b4bb-11eb-8b60-1f46deccb307.png">

**Comment by aneudecker** [comment]
@claycantrell Thanks for the details. You are right, this is a bug that was introduced in version 0.5.0 of the package.

You can disable the names by setting `rows = list(names = FALSE)`, `cols = list(names = FALSE)` using the package version 0.5.1 that I just uploaded on GitHub. You can install using `devtools::install_github("INWTlab/shiny-matrix")`.

Hope this solves your issues!

**Comment by trodgers0131** [comment]
It's a very handy tool btw. We're definitely putting it to good use. Keep up the good work!

**Comment by aneudecker** [comment]
0.6.0 has been released to CRAN. This resolves this issue.
