### ISSUE TITLE
Can't set rows.names as FALSE on v0.5.0

### ISSUE THREAD

**Issue by ruthkr** [INWTlab/shiny-matrix#19]
Hi! Thank you for the package, it's been really helpful.

Apart from the broken table style (#18), I found that  
```r
shinyMatrix::matrixInput(
  ...,
  rows = list(names = FALSE)
)
``` 
doesn't work on the 0.5.0 release, as the rownames are always displayed.

I checked on the 0.4.0 (https://github.com/INWTlab/shiny-matrix/commit/d79f887b79df3eb2ebe474b1e83aa6c233c03fdb), and the `names` parameter works as expected.

Thanks 😃

**Comment by aneudecker** [comment]
@ruthkr Thanks for reporting this. You are absolutely right - the feature got lost during the refactoring of the field. I uploaded a new version 0.5.1 to GitHub to fix this.

**Comment by ruthkr** [comment]
Hi @aneudecker, 

Thanks a lot for responding and fixing it very quickly. I really appreciate it. 
I have installed the newest version (the 0.5.1 release), and it worked perfectly. 
Thank you very much!
