### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by jfgomezok** [INWTlab/shiny-matrix#2]
Unable to install the package from CRAN:

`install.packages("shinyMatrix")` returns:

> Installing package into ‘C:/Users/jgomez/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘shinyMatrix’ is not available (for R version 3.5.1)
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'

Also, when I tried with his one: `if (require("devtools")) install_github("INWTlab/shinyMatrix")`, the result was also an error:

> Downloading GitHub repo INWTlab/shinyMatrix@master
from URL https://api.github.com/repos/INWTlab/shinyMatrix/zipball/master
Installation failed: Not Found (404)

**Comment by SarahWagner** [comment]
@jfgomezok Thanks for reporting. 

If you try `devtools::install_github("INWTlab/shiny-matrix")` it should work. This is a typo, sorry for that. I'll update the readme accordingly. 
The download from CRAN works for me, have you tried another mirror?

**Comment by aneudecker** [comment]
Issue fixed by commit 2895898a3157f9069ec53b5d4052c750902b6b91
