### ISSUE TITLE
Bug when using extend feature for rows in the matrix

### ISSUE THREAD

**Issue by lgirola** [INWTlab/shiny-matrix#21]
Hi, shinyMatrix really fits my needs. Thank you for this! Perhaps I´m not using the app correctly, or maybe it´s a bug. But when I use the extend feature for inserting additional rows into a matrix, it only works if I click on the right-most field of the new row. If I click on any other field (to the left of the right-most) of the new row, then the matrix is left with invalid fields in that row and there´s no way to go back and fix it other than starting all over again. Below is the code I´m using.  I also screen shot an example of what happens when I click on any column other than the right-most: a successful row insertion is shown in blue, an unsuccessful row insertion shown in red.

```
library(shinyMatrix)
m <- diag(5)
colnames(m) <- 1:5
rownames(m) <- letters[1:5]

ui <- fluidPage(
        titlePanel("Demonstration Matrix Input Field"),
        fluidRow(
          column(6, matrixInput(
                      inputId = "matrix",
                      label = "Default matrix",
                      value = m,
                      class = "numeric",
                      cols = list(names = TRUE),
                      rows = list(extend = TRUE,names = TRUE) # change "extend" to TRUE
                    )
          ),
          column(6, tableOutput("table"))
        )
      )

server <- function(input, output, session) {
            output$table <- renderTable(input$matrix, rownames = TRUE)
          }

shinyApp(ui, server)
```
Attached image: 
![shinyMatrix](https://user-images.githubusercontent.com/84516599/119023344-05ea1700-b9a2-11eb-9239-f3540ff8a382.png)

**Comment by aneudecker** [comment]
Hi @lgirola,

glad to hear that the package is used!

We did some major restructuring for version 0.5.0 to make the JavaScript part more maintainable. This probably introduced this bug. Thanks for your detailed report, I will look into it

**Comment by aneudecker** [comment]
@lgirola The new version 0.6.1 on GitHub should solve your problem. It will eventually find its way to CRAN. Until then you can install the version from GitHub using `devtools::install_github('INWTlab/shiny-matrix')`

**Comment by lgirola** [comment]
Hi Andreas,

I just downloaded the new version 0.6.1 as instructed, but the issue persists when I run it. (Btw I uninstalled the prior version of shinyMatrix first, then installed 0.6.1).

In summary, when using the extend feature for additional row inputs (an extremely handy feature), I have to click on the right-most field first before inserting any values in the fields to the left of it. If I first click on any new field to the left of the right-most field, all fields to the right disappear and are no longer available for data entry. Ideally, one should be able to click on any new field for inserting data.

Kind regards,

L. Girola

-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


May 21, 2021, 08:29 by ***@***.***:

**Comment by aneudecker** [comment]
@lgirola did you try clearing the browser cache? Maybe there is an old JavaScript file being used

**Comment by lgirola** [comment]
Ahhhh yes that fixed it! Clearing the cache worked. Thank you so much for your prompt responses and resolutions. I really need this package, perfectly fits my needs.

**Comment by nanxstats** [comment]
Is it possible that we do a CRAN submission anytime soon? This seems to be a critical issue affecting a major feature of the widget. Thanks!

**Comment by yihui** [comment]
I'm here to confirm that this bug has been fixed in the latest CRAN version of shinyMatrix. Thanks!
