### ISSUE TITLE
More of a question than issue: how to hide row header column in shinyMatrix?

### ISSUE THREAD

**Issue by lgirola** [INWTlab/shiny-matrix#22]
Hi! When generating an input matrix, is it possible to hide or eliminate the left-most column for row headers? If not possible, are there other ways to adjust it (obfuscate it) by other means such as narrowing, filling in with color, etc.?

Below is simple R code that generates the matrix pictured at the bottom:

```
library(shiny)
library(shinyMatrix)

m <- matrix(runif(12), 6, 2, dimnames = list(NULL, c("x", "y"))) 
ui <- fluidPage(   
  titlePanel("shinyMatrix: Simple App"),   
  sidebarPanel(     
    width = 6,     
    tags$h4("Input matrix"),     
    matrixInput("sample",value = m,rows = list(extend = TRUE),cols = list(names = TRUE))
    ),   
  mainPanel(     
    width = 6,plotOutput("scatter")) 
  ) 

server <- function(input, output, session) {   
  output$scatter <- renderPlot({     
    plot(input$sample, col = "red", main = "Scatterplot")}) 
  } 

shinyApp(ui, server)

```
And now the output image:

![shinyMatrix](https://user-images.githubusercontent.com/84516599/119453379-a7bd8b00-bd37-11eb-82d8-2abf00e1a095.png)

**Comment by aneudecker** [comment]
@lgirola Settings `rows = list(extend = TRUE, names = FALSE)` should do the trick

**Comment by lgirola** [comment]
Perfect! Works and looks great, I rely heavily on your package. I love matrices. Thank you for this!
