### ISSUE TITLE
`.vue-input td` class seems to overrule border-left and border-top attribute

### ISSUE THREAD

**Issue by jassler** [INWTlab/shiny-matrix#25]
I have the following example:

```R
slibrary(shiny)

ui <- fluidPage(
  tags$style('#mat td, #mat th { border-left: 1px solid red; border-top: 1px solid red; }'),
  shinyMatrix::matrixInput(
    'mat', value = matrix(1:20, nrow = 4)
  )
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

From this I would assume that for each table cell its left and top border are marked red. However this applies only for the outermost border to the left and to the top.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/24298790/137223179-0c608e0e-b815-4706-9fe1-9e688bf7c76c.png">

I was able to get the expected behavior when disabling the border attribute of `.vue-input td` in the developer tools.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/24298790/137227546-d1159714-5719-4e75-9b90-dcd019fa06a2.png">

Overall setting borders seems a little inconsistent to me. For instance how would I go about making every border invisible except for a specific cell?

**Comment by jassler** [comment]
I was able to get back the expected behavior by overriding vue's css in my own stylesheet.

```css
.vue-input td, .vue-input th {
  border: none;
}
```

That's probably a hack, but I don't know any other way around right now.

**Comment by aneudecker** [comment]
@jassler Glad you figered out the "hack". Typically when using css from sources you would need some kind of overrides like yours, I do not have a better solution.

The solution you wrote is using the "be more specific" override for CSS. You could also use `!important` to force the border
```
<selector> {
border-left: 1px solid red !important;
}
