### ISSUE TITLE
Input only shown when clicking on next cell, but not when using Tab or enter

### ISSUE THREAD

**Issue by mhbuss** [INWTlab/shiny-matrix#30]
Hi,

I've got a question: I implemented shiny-matrix in my app and it's a really great extension. I've got one question though: When I enter a value in the matrix, the entered value is only shown when I click on the next cell but not when I use Tab or Enter. Is there a way to fix this? If that is not possible, would it be possible to prevent the user from using "Tab" or "Enter" while working on the matrix?

Thanks in advance!

**Comment by SarahWagner** [comment]
Hey @mhbuss, in fact `shinyMatrix` does support tabbing and I can not reproduce the behaviour you describe. Please provide a minimal reproducible example and your session info.

**Comment by mhbuss** [comment]
Hi @SarahWagner, it seems that this is a problem that only occurs on my Mac (both if I run the app locally and on the server). Very weird and I haven't been able to figure out the reason for this. Other users don't seem to have this problem so far. Thanks for your support though.

**Comment by amitghosh-inwt** [comment]
Maybe you can check using a different browser on your Mac (e.g. Firefox instead Safari) to see if it could be related to any security settings in your browser?

**Comment by mhbuss** [comment]
Indeed, the problem seems to occur only with Firefox. I'll let you know in case others run into the same problem in the course of our research project. Thanks!

**Comment by hamgamb** [comment]
I've ran into the same issue with Firefox, where a cell does not appear to update if the enter key is used to go to another cell. 

The issue can be replicated with the following app, running in Firefox. 

1. Enter any numeric in cell A, 2023
2. Press enter
3. The numeric in cell A, 2023 returns to 0
4. Click cell A,2023
5. The numeric in cell A,2023 returns to the numeric entered in step 1. 

Alternatively:

1. Enter any numeric in cell A, 2023
2. Click cell B, 2023

Works as expected. 

``` r
library(shiny)
library(shinyMatrix)

ui <- fluidPage(
  fluidRow(
    matrixInput("matrix",
                class = "numeric",
                cols = list(
                  names = TRUE,
                  extend = TRUE,
                  editableNames = FALSE,
                  delta = 0,
                  delete = TRUE
                ),
                rows = list(
                  names = TRUE,
                  extend = TRUE,
                  editableNames = FALSE,
                  delta = 0,
                  delete = FALSE
                ),
                value = matrix(0, nrow = 19, ncol = 1, dimnames = list(LETTERS[1:19], 2023))
    )
  )
)

server <- function(input, output, session) {
  output$table <- renderTable(input$matrix)
}

shinyApp(ui = ui, server = server)
#> 
#> Listening on http://127.0.0.1:3749
```

<sup>Created on 2023-01-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyMatrix_0.6.2 shiny_1.7.1      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        jquerylib_0.1.4   bslib_0.4.1       pillar_1.8.1      compiler_4.0.2    later_1.3.0       R.methodsS3_1.8.2
 [8] R.utils_2.11.0    tools_4.0.2       digest_0.6.30     memoise_2.0.1     jsonlite_1.8.0    lifecycle_1.0.3   tibble_3.1.8     
[15] R.cache_0.16.0    pkgconfig_2.0.3   rlang_1.0.6       reprex_2.0.1      cli_3.4.1         rstudioapi_0.13   xfun_0.35        
[22] fastmap_1.1.0     withr_2.5.0       styler_1.7.0      knitr_1.41        sass_0.4.4        fs_1.5.2          vctrs_0.5.1      
[29] glue_1.6.2        R6_2.5.1          fansi_1.0.3       purrr_0.3.5       clipr_0.8.0       magrittr_2.0.3    promises_1.2.0.1 
[36] htmltools_0.5.2   ellipsis_0.3.2    rsconnect_0.8.26  mime_0.12         xtable_1.8-4      httpuv_1.6.5      utf8_1.2.2       
[43] cachem_1.0.6      R.oo_1.25.0   
```

**Comment by aneudecker** [comment]
@hamgamb Thanks for the report! I could reproduce the issue on Firefox using your minimal example and try to implement a fix

**Comment by aneudecker** [comment]
@hamgamb I pushed a fix to GitHub (Version 0.6.3). Could you try if this resolves your issues?

**Comment by hamgamb** [comment]
@aneudecker looks good to me! Thanks for your quick response, and for a great package!

**Comment by aneudecker** [comment]
Perfect. It will find it's way to CRAN. Until then, please use the GitHub version. Thanks!
