### ISSUE TITLE
Copy and pasting between Excel and shinyInput

### ISSUE THREAD

**Issue by Braberibas** [INWTlab/shiny-matrix#32]
The documentation for shinyMatrix states that one can copy and paste data from table applications into an app using shinyMatrix. However, I appear to be unable to do so. With the app, the code of which is provided below, I am unable to copy and paste ranges of cells between Excel and the shiny app. I couldn't find any arguments in the help page for `shinyInput` to enable copy and pasting. Am I misunderstanding how copy and paste should work, or am I doing something wrong? I would appreciate any guidance.

```library("shiny") 
library("shinyMatrix") 
m <- matrix(rep(0.0025, 4), nrow = 2,
              dimnames = list(c("A","B"), c("A","B")))
ui <- fluidPage(sidebarPanel(width = 6, 
                             matrixInput("sample", 
                                         value = m,
                                         label = "Paste your data below:",
                                         class = "numeric")))
server <- function(input, output, session) {
  #intentionally empty
  } 
shinyApp(ui, server)

**Comment by aneudecker** [comment]
@Braberibas I am afraid that the documentation is outdated. I just realised that we still mention it in the README. We removed the functionality in version 0.3.0 as it did not work reliably and was causing more issues than we expected.

I am updating the README and closing this.

Sorry for the inconvenience
