### ISSUE TITLE
Control number of decimals

### ISSUE THREAD

**Issue by stla** [INWTlab/shiny-matrix#36]
Hello,

I think it would be nice to have the possibility to control the number of decimals of the displayed numeric cell values.

I don't know Vue, but maybe:
```js
<span v-else>{{ value.toFixed(ndigits) }}</span>
```
The number of digits for each cell could be given as an option in a matrix.

**Comment by aneudecker** [comment]
I like the idea. We need to decide however if we want to use a generic approac with the option to add any formatting function or if we focus on your use case. I would imagine if we implement only the option to control the number of decimals the next request would be to change the digits and thousands separator. So maybe a more generic way would be better

**Comment by stla** [comment]
I understand and I agree. Maybe adding a JavaScript dependency like **d3.format** would be nice (a library to format numbers).

**Comment by aneudecker** [comment]
That sounds good. We could give the possibility to pass the format as string like format=".1f" and pass this to d3.format

**Comment by aneudecker** [comment]
@stla with the current version on GitHub (0.8.0) you can now format the cells.
