### ISSUE TITLE
Label to matrixInput

### ISSUE THREAD

**Issue by massonix** [INWTlab/shiny-matrix#6]
Hi,

Is it possible to add a label to the matrixInput function? This seems to be a common parameter in input functions in shiny (https://mastering-shiny.org/basic-ui.html).

Thanks,

Ramon

**Comment by aneudecker** [comment]
Hi Ramon,

thanks for this suggestion. We did not need this parameter yet but it makes sense to include it to increase consistency. For now you could use some custom ui wrapper function. I'll implement it though in near future.

**Comment by massonix** [comment]
Thanks a lot!

**Comment by aneudecker** [comment]
@massonix Added with https://github.com/INWTlab/shiny-matrix/commit/f68e2b119d96b407ac83359d3ebde5f27be84e4e

**Comment by massonix** [comment]
Perfect! I will use it!
